### ISSUE TITLE
Server is down: 404

### ISSUE THREAD

**Issue by brennanerbz** [bananaoomarang/isomorphic-redux#12]
Looks like the API_URL is invalid. Getting 404 error that I can't POST.

`18:38:59.460 Object { data: "Cannot POST /redux-tutorial-backend…", status: 404, statusText: "Not Found", headers: Object, config: Object }1 bundle.js:40481:10`

**Comment by bananaoomarang** [comment]
https://github.com/bananaoomarang/isomorphic-redux/issues/13
