### ISSUE TITLE
"Cannot POST /redux-tutorial-backend?webtask_no_cache=1↵"

### ISSUE THREAD

**Issue by AlexHandy1** [bananaoomarang/isomorphic-redux#13]
Getting above error "Cannot POST /redux-tutorial-backend?webtask_no_cache=1↵" when try to add actions from after cloning and npm installing.
What is best approach to replace the below external database link? 
Also, how does this relate to your MongoDB set-up?

```
const API_URL = 'https://webtask.it.auth0.com/api/run/wt-milomord-gmail_com-0/redux-tutorial-backend?webtask_no_cache=1';
```

**Comment by bananaoomarang** [comment]
From what I can see Webtasks had some issues today. I think this should be fixed now/soon, and everything will be back to normal. 

Re how, It's using a [webtask](https://webtask.io/) to interface with an external Mongo instance at mongolabs. Neat trick to avoid deploying another server just for fun.
