### ISSUE TITLE
async actions

### ISSUE THREAD

**Issue by lalitkapoor** [bananaoomarang/isomorphic-redux#2]
How would you handle passing the state to the client if the actions were async?

**Comment by bananaoomarang** [comment]
I just updated to repository to be in line with what I'm doing [here](https://github.com/bananaoomarang/chapters)

Which makes this easier, though I haven't gotten round to implementing it yet. At the moment my plan is to assign required async actions somehow to the components. Something like: 

``` javascript
static asyncActions = [actionCreator1, actionCreator2]
```

Then wait for a promise queue to finish before sending the response from the server.

But first I'm going to fix the ugly `actionCreator()(this.props.dispatch)` by wrapping async actions in promises and using some [Redux middleware](https://github.com/gaearon/redux/issues/99#issuecomment-112212639).
