### ISSUE TITLE
getTodos() called twice on the server side

### ISSUE THREAD

**Issue by Dattaya** [bananaoomarang/isomorphic-redux#20]
`babel` or some other library copies all the properties from the wrapped component into the wrapper:
![2015-10-21_14h32_33](https://cloud.githubusercontent.com/assets/387256/10639691/3ae5f99e-781a-11e5-848f-1c4d97e07f07.png)
and this piece of code adds both `current.needs` and `current.WrappedComponent.needs` to the final array:

``` javascript
    return (current.needs || [])
      .concat((current.WrappedComponent ? current.WrappedComponent.needs : []) || [])
      .concat(prev);
```

Therefore, this is what we have in the middleware:
![2015-10-21_14h33_05](https://cloud.githubusercontent.com/assets/387256/10639796/a3f11f7c-781a-11e5-9bdf-264535d48f36.png)

and since the Todo reducer concats received todos with `state.concat` instead of creating a new List `return new Immutable.List(action.res.data);`, that's the result:
![2015-10-21_17h32_07](https://cloud.githubusercontent.com/assets/387256/10639895/07008080-781b-11e5-98c3-f21cac926863.png)

Please, confirm whether you see this behavior or maybe it's something wrong with my setup.

**Comment by cport1** [comment]
Yup, I see this as well.

**Comment by Dattaya** [comment]
I can send a PR, but it seems @bananaoomarang doesn't have enough time at the moment to support this project as my previous pull request is still unanswered.

**Comment by andystalick** [comment]
I'd be curious to see your PR, even if it doesn't get merged, @Dattaya

**Comment by cport1** [comment]
I am curious to see your solution too.

**Comment by Dattaya** [comment]
@andystalick, @cport1 it's very simple for now, this is my `fetchComponentData`:

``` javascript
export default function fetchComponentData(dispatch, components, params) {
  const needs = components.reduce((prev, current) => {
    return current ? (current.needs || []).concat(prev) : prev;
  }, []);

  const promises = needs.map(need => dispatch(need(params)));

  return Promise.all(promises);
}

```

I check `current` because one of my react-router's `onEnter` hook might return null in the array and I don't want to overcomplicate it, just easier to test it here. Also note that I haven't tested this code thoroughly.

**Comment by Dattaya** [comment]
Forgot to add that I had slightly changed todo reducer too:

``` javascript
export default function reducer(state = defaultState, action) {
  switch (action.type) {
    case GET_TODOS:
      return new Immutable.List(action.res.data);
...
```

**Comment by bananaoomarang** [comment]
Yes, this is an issue. Sorry about not getting back to people, life has been pretty hectic the past couple of months!

**Comment by cport1** [comment]
What would the process be to have an immutable list of objects instead of just an array of strings? Currently, when I try to do this I get::

"Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:"

**Comment by Dattaya** [comment]
@cport1, you can use other Immutable.js data structures, for example you can create a List of Maps. Map is an unordered key-value iterable. Here's documentation: https://facebook.github.io/immutable-js/docs/#/

**Comment by Dattaya** [comment]
This mistake might happen when you change some part of the app, it gets hot reloaded, and then if you reload the page, this warning will pop up because the server had been started without those changes but the client is up to date. Try to stop the server and run it again. For production, run `npm run build` again. Is this the case?

**Comment by Dattaya** [comment]
@cport1 maybe you can post here a piece of code that's causing the trouble and I'll try to use it myself.

**Comment by cport1** [comment]
import Immutable from 'immutable';
const defaultState = new Immutable.Map();
export default function TodoReducer(state = defaultState, action) {
    switch(action.type) {
        case 'GET_TODO':
            return state = new Immutable.Map(action.res.data);

Just something like this in my reducer gets me "Using Maps as children is not yet fully supported. It is an experimental feature that might be removed. Convert it to a sequence / iterable of keyed ReactElements instead."

**Comment by Dattaya** [comment]
try this:

``` javascript
  return state = Immutable.fromJS(action.res.data)
```

or something like this:

``` javascript
  return state = Immutable.List(action.res.data.map(todo => Immutable.Map(todo)))
```

Haven't tested it in the console but this is the basic idea. The result of both of these should be a `List` of `Map`s (provided `res.data` is an array of objects). Immutable.js docs also have an example of how to update these nested structures https://facebook.github.io/immutable-js/#nested-structures.

**Comment by cport1** [comment]
todo.get('title') works in the view now, but I get todo.get is not a function when I try to post in the CREATE_TODO

**Comment by Dattaya** [comment]
@cport1 your action should return a todo object and you can add it in CREATE_TODO, I think like so: `state.concat(Immutable.Map(todo))`

**Comment by cport1** [comment]
I have todo.get('title') in my TodosView ... it works when I initially load the app, but it breaks when I do CREATE_TODO. That's where I get the error TypeError: todo.get is not a function

return (
                            <div style={btnStyle} key={index}>
                                <div>{todo.get('title')}</div>
                            </div>
            );

**Comment by Dattaya** [comment]
Did you change your `createTodo` action creator and a part of the todo reducer responsible for updating the state when `case CREATE_TODO:` appropriately?

**Comment by cport1** [comment]
I got it to work by doing return state.concat(Immutable.List(action.res.data.map(todo => Immutable.Map(todo)))); in my reducer

**Comment by Alex-Shilman** [comment]
@Dattaya ,

What debugging tool are you using to display the current component with props like that?
Thanks

**Comment by Dattaya** [comment]
@Alex-Shilman, it's Webstorm's built-in debugger. You can see it in action here: https://www.youtube.com/watch?v=CdXoeVRN1JU though they seem to be debugging client code, not node.js.
