### ISSUE TITLE
Removing initial pushState to /home

### ISSUE THREAD

**Issue by beinginorbit** [bananaoomarang/isomorphic-redux#28]
Hello,

I'm curious how to remove pushState to /home URI. I tried just commenting it out and it makes fetchComponentData "current" throw an undefined error.

**Comment by Dattaya** [comment]
That's weird, try to apply this PR #25 what's the result?

**Comment by beinginorbit** [comment]
That works, I realize it was something else I changed shortly after I posted this. Thanks for the quick response though. This is probably a good PR to include :)

**Comment by beinginorbit** [comment]
@Dattaya I'm going to create another issue for what I am experiencing and maybe you can help. :)

**Comment by Dattaya** [comment]
gladly, but not necessarily immediately as it's too late in my timezone.

**Comment by beinginorbit** [comment]
@Dattaya I can't reproduce... you're off the hook, thanks again. :)

**Comment by Dattaya** [comment]
yep, magic happens :smiley:
