### ISSUE TITLE
How can I run this demo on windows?

### ISSUE THREAD

**Issue by zjdgx** [bananaoomarang/isomorphic-redux#32]
I can't run this demo on windows as I don't know how to run node --harmony with path. Please help me to run this demo on windows. thanks!

**Comment by Dattaya** [comment]
@zjdgx, add this to the `scripts` section in `package.json`:

``` javascript
    "wstart": "set NODE_ENV=production&& set NODE_PATH=./shared&& node --harmony .",
    "wdev": "set NODE_PATH=./shared&& node --harmony .",
    "wbuild": "set NODE_ENV=production&& webpack --progress --color -p --config webpack.prod.config.js"
```

That should do it. Now, to run the app in, say, a dev mode, type in the terminal `npm run wdev`.

**Comment by zjdgx** [comment]
@Dattaya thank you very much! It works for me! BTW, where did you get this code?

**Comment by Dattaya** [comment]
You are very welcome. 

> BTW, where did you get this code?

I made it myself.

**Comment by zjdgx** [comment]
Ok, thanks again!
