### ISSUE TITLE
Use babel6 ?

### ISSUE THREAD

**Issue by carloscuatin** [bananaoomarang/isomorphic-redux#34]
hrm is compatible with babel6, make upgrade ?

**Comment by Dattaya** [comment]
I've upgraded [my branch](https://github.com/Dattaya/isomorphic-redux/commit/37334223dfc1595c0a15527aa65b6e8aba09b7df) to babel 6 and I can send an upgrade to this repo, provided you are interested, @bananaoomarang.

**Comment by bananaoomarang** [comment]
Just pushed this, was holding off because I didn't know about `tranform-decorators-legacy`, but that seems to work :)

**Comment by Dattaya** [comment]
Great :+1: 
`tranform-decorators-legacy` now seems to be mature enough and work in most of the cases.
