### ISSUE TITLE
Unhandled 'error' event      

### ISSUE THREAD

**Issue by brw31415** [bananaoomarang/isomorphic-redux#35]
npm WARN EPEERINVALID react-router@1.0.2 requires a peer of history@1.13.x but none was installed.
brw314@Lydia:isomorphic-redux$ npm run dev                                                               

> isomorphic-redux@1.0.0 dev /home/brw314/react/isomorphic-redux  
> NODE_PATH=$NODE_PATH:./shared node --harmony .                                                         

events.js:141
      throw er; // Unhandled 'error' event  
      ^                                                                                                  

Error: listen EADDRINUSE :::5030  
    at Object.exports._errnoException (util.js:856:11)  
    at exports._exceptionWithHostPort (util.js:879:20)  
    at Server._listen2 (net.js:1234:14)  
    at listen (net.js:1270:10)  
    at Server.listen (net.js:1366:5)  
    at EventEmitter.listen (/home/brw314/react/isomorphic-redux/node_modules/express/lib/application.js:6
17:24)  
    at Object.<anonymous> (/home/brw314/react/isomorphic-redux/index.js:9:8)  
    at Module._compile (module.js:425:26)  
    at Object.Module._extensions..js (module.js:432:10)  
    at Module.load (module.js:356:32)                                                                    

npm ERR! Linux 4.1.0-insomnia247
npm ERR! argv "/home/brw314/.node_local/bin/node" "/home/brw314/.node_local/bin/npm" "run" "dev"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! isomorphic-redux@1.0.0 dev: `NODE_PATH=$NODE_PATH:./shared node --harmony .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the isomorphic-redux@1.0.0 dev script 'NODE_PATH=$NODE_PATH:./shared node --harmony .'
.  
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the isomorphic-redux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_PATH=$NODE_PATH:./shared node --harmony .
npm ERR! You can get their info via:
npm ERR!     npm owner ls isomorphic-redux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/brw314/react/isomorphic-redux/npm-debug.log
br

**Comment by Dattaya** [comment]
That's easily fixable, replace this line https://github.com/bananaoomarang/isomorphic-redux/blob/master/package.json#L26 with 

``` javascript
"history": "1.13.1",
```
