### ISSUE TITLE
Failed propTypes

### ISSUE THREAD

**Issue by schlaus** [bananaoomarang/isomorphic-redux#41]
Thanks for the great tutorial!

However even without any modifications this example is throwing two warnings:

> Warning: Failed propType: Required prop `todos` was not specified in `Connect(Home)`. Check the render method of `RoutingContext`.
> 
> Warning: Failed propType: Required prop `dispatch` was not specified in `Connect(Home)`. Check the render method of `RoutingContext`.

Could someone enlighten a React noob as to how to fix it? (besides removing the `propTypes` [definition](https://github.com/bananaoomarang/isomorphic-redux/blob/master/shared/components/Home.jsx#L11-L14), which is the best I could come up with...)

**Comment by jaydenseric** [comment]
I immediately ran into the same issue.

**Comment by chungchiehlun** [comment]
I just fixed it and sent [pull request](https://github.com/bananaoomarang/isomorphic-redux/pull/43).

**Comment by bananaoomarang** [comment]
Just merged this
