### ISSUE TITLE
App may be broken with Babel ^6.4.0

### ISSUE THREAD

**Issue by DavidWells** [bananaoomarang/isomorphic-redux#44]
Just an FYI.  See: https://github.com/feross/standard/issues/372 && https://github.com/davezuko/react-redux-starter-kit/issues/405

The app is throwing me this error when trying to run

```
      ^
SyntaxError: /isomorphic-redux/shared/components/Home.jsx: A semicolon is required after a class property (14:3)
  12 |     todos:    PropTypes.any.isRequired,
  13 |     dispatch: PropTypes.func.isRequired
> 14 |   }
     |    ^
```

Great post on this BTW! =)

**Comment by bananaoomarang** [comment]
Just merged a pull request which should fix this

Glad you liked this post :)
