### ISSUE TITLE
Can't change output folder in webpack.dev.js

### ISSUE THREAD

**Issue by thngdude** [bananaoomarang/isomorphic-redux#49]
Thanks for starting this project. It has been helpful with understanding isomorphic concepts.

I'm trying to change the output folder of the bundle in webpack.dev.js and it's not working. 

```
output: {
      path: path.resolve(__dirname, 'dist'),
      publicPath: path.resolve(__dirname, 'dist')
    },

```

If I reference "/dist/bundle.js" in my html, it doesn't work, but "bundle.js" still works. It seems to ignore my configuration. 

Any advice why this is happening? Thanks.

**Comment by Dattaya** [comment]
@thngdude additionally you need to pass public path to the `webpackDevMiddleware` as I did here [webpack.dev.js#L38](https://github.com/Dattaya/isomorphic-redux-plus/blob/master/webpack.dev.js#L38):

``` javascript
app.use(webpackDevMiddleware(compiler, {noInfo: true, publicPath: config.output.publicPath}));
```

also see if you don't need to change the base path of the express static middleware  in `server.jsx`: 

``` javascript

app.use(express.static(path.join(__dirname, 'static')));
```

**Comment by thngdude** [comment]
Works like a charm. Thanks!
