### ISSUE TITLE
Render dynamic route on the server

### ISSUE THREAD

**Issue by yungrich** [bananaoomarang/isomorphic-redux#52]
How would you render a dynamic route on a hypothetical TodosView.js component? (example localhost:3000/todos/1 where 1 is the id of the todo item)

On Home you used:
static needs = [ TodosActions.getTodos ];

On TodosView, how would you get the parameter ( 1 in this case ), and then pass it to the viewTodo(id) action so that it can be rendered on the server?

**Comment by yungrich** [comment]
[solved] you can delete this issue

Great work on this repo btw loving it

**Comment by bananaoomarang** [comment]
Thanks, glad you find it useful :)

**Comment by iroy2000** [comment]
@alleversun how do you solve that issue??  It would be helpful if you document here as well. 

Thanks
