### ISSUE TITLE
Objects are not valid as a React child (found: object with keys {})....

### ISSUE THREAD

**Issue by veeracs** [bananaoomarang/isomorphic-redux#53]
Getting following error in dev mode and minification error in prod mode.

Objects are not valid as a React child (found: object with keys {}). If yo u meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `TodosView`.

**Comment by bananaoomarang** [comment]
I'm afraid I can't reproduce on my machine. It could be to do with your Node version, I suppose (I'm on `5.8.0`),  it also looks like it could be an inconsistency in how Babel is doing the transform.

You could try `rm -rf`ing `node_modules` and re-installing the dependencies.

Also make sure your `TodosView` code is the same as the one in the repo, there could be a typo there.

**Comment by veeracs** [comment]
Thanks, closing the issue, rm -rf node_modules and npm install helped.
