### ISSUE TITLE
link to React-lego as an example?

### ISSUE THREAD

**Issue by peter-mouland** [bananaoomarang/isomorphic-redux#64]
Hi,  I have implemented the concepts you talk about in the blog post and implemented them in an example project.  Would you be kind enough to link to [React-lego](https://github.com/peter-mouland/react-lego)?

As a quick intro, I started the project to help people implement ideas and new techs one piece at a time.  I found many starter-apps or boiler-plates etc were often all singing / all dancing and could be hard to disect.

The section/branch which implements the promise-middle ware is https://github.com/peter-mouland/react-lego#redux-with-promise-middleware

**Comment by bananaoomarang** [comment]
Hi Peter, not around my laptop ATM but React-lego sounds like a cool idea I’ll have a look at adding this. Thanks!

**Comment by govind999** [comment]
@peter-mouland  what are the advantages we get if you link to React-lego? i am using this repo as an example for our isomorphic app, i am going through react logo repo also, its interesting.

**Comment by peter-mouland** [comment]
I just thought it might help people out. 

I know sometimes I try things out and miss something that looks innocuous; so seeing another repo doing the same thing, but in a slightly different way, might help.

**Comment by govind999** [comment]
@peter-mouland  do you know where is the master repo for react-lego which has redux ect integrated, 

This one has only the basic one https://github.com/peter-mouland/react-lego

**Comment by govind999** [comment]
@bananaoomarang is hot reloading working on this module?

**Comment by peter-mouland** [comment]
yeah, in the react-hot-loading branch: https://github.com/peter-mouland/react-lego#hot-reloading

**Comment by govind999** [comment]
@peter-mouland @bananaoomarang do you guys worked on i18 integration for react? if so can you point me to some tutorials?
