### ISSUE TITLE
I am new to react and i am creating a SSR app when try to build on server i got following... please help....

### ISSUE THREAD

**Issue by ghost** [bananaoomarang/isomorphic-redux#73]
$ npm run dev

> my-ssr-app@0.1.0 dev /home/nemi/my-ssr-app
> npm-run-all --parallel build dev:*

ERROR: Task not found: "build"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-ssr-app@0.1.0 dev: `npm-run-all --parallel build dev:*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-ssr-app@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nemi/.npm/_logs/2019-12-24T10_45_57_344Z-debug.log

**Comment by bananaoomarang** [comment]
Hi! I would actually not recommend this project for use today! If you are looking for a nice way to create an SSR app I can recommend https://nextjs.org/
